# Generated by Django 5.2.16 on 2026-07-15 16:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('documents', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Education',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('degree_level', models.CharField(choices=[('s1', 'S1'), ('s2', 'S2'), ('s3', 'S3'), ('postdoc', 'Postdoc')], max_length=10)),
                ('institution', models.CharField(max_length=255)),
                ('program', models.CharField(max_length=255)),
                ('country', models.CharField(max_length=100)),
                ('start_year', models.PositiveIntegerField()),
                ('end_year', models.PositiveIntegerField(blank=True, null=True)),
                ('thesis_title', models.CharField(blank=True, max_length=500)),
                ('gpa', models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True)),
                ('is_public', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ['-start_year'],
            },
        ),
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('category', models.CharField(choices=[('technical', 'Technical'), ('language', 'Language'), ('research', 'Research')], max_length=20)),
                ('proficiency', models.PositiveSmallIntegerField(help_text='1 (basic) to 5 (expert)')),
                ('is_public', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ['category', '-proficiency'],
            },
        ),
        migrations.CreateModel(
            name='Achievement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('issuer', models.CharField(max_length=255)),
                ('level', models.CharField(choices=[('institutional', 'Institutional'), ('national', 'National'), ('international', 'International')], max_length=20)),
                ('date', models.DateField()),
                ('description', models.TextField(blank=True)),
                ('is_public', models.BooleanField(default=False)),
                ('certificate', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='achievements', to='documents.document')),
            ],
            options={
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='Position',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('organization', models.CharField(max_length=255)),
                ('category', models.CharField(choices=[('structural', 'Structural'), ('functional', 'Functional'), ('organizational', 'Organizational'), ('professional', 'Professional')], max_length=20)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField(blank=True, help_text='Leave blank if current', null=True)),
                ('description', models.TextField(blank=True)),
                ('is_public', models.BooleanField(default=False)),
                ('sk_document', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='positions', to='documents.document')),
            ],
            options={
                'ordering': ['-start_date'],
            },
        ),
        migrations.CreateModel(
            name='TrainingCertification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('provider', models.CharField(max_length=255)),
                ('date', models.DateField()),
                ('expiry_date', models.DateField(blank=True, null=True)),
                ('is_public', models.BooleanField(default=False)),
                ('certificate', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='training_certifications', to='documents.document')),
            ],
            options={
                'ordering': ['-date'],
            },
        ),
    ]
