# Generated by Django 5.2.16 on 2026-07-17 02:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cv', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='education',
            name='degree_level',
            field=models.CharField(choices=[('d3', 'D3'), ('s1', 'S1'), ('s2', 'S2'), ('s3', 'S3'), ('postdoc', 'Postdoc')], max_length=10),
        ),
    ]
