# Generated by Django 5.2.16 on 2026-07-15 16:15

import apps.accounts.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=200)),
                ('title_prefix', models.CharField(blank=True, help_text='e.g. "Dr."', max_length=30)),
                ('title_suffix', models.CharField(blank=True, help_text='e.g. "M.Kom"', max_length=60)),
                ('nidn', models.CharField(blank=True, max_length=30, verbose_name='NIDN')),
                ('nip', models.CharField(blank=True, max_length=30, verbose_name='NIP')),
                ('orcid', models.CharField(blank=True, max_length=50, verbose_name='ORCID')),
                ('scopus_id', models.CharField(blank=True, max_length=50, verbose_name='Scopus ID')),
                ('sinta_id', models.CharField(blank=True, max_length=50, verbose_name='SINTA ID')),
                ('google_scholar_id', models.CharField(blank=True, max_length=50, verbose_name='Google Scholar ID')),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('phone', models.CharField(blank=True, max_length=30)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='profile/')),
                ('bio', models.TextField(blank=True)),
                ('institution', models.CharField(blank=True, max_length=200)),
                ('faculty', models.CharField(blank=True, max_length=200)),
                ('department', models.CharField(blank=True, max_length=200)),
                ('current_position', models.CharField(blank=True, max_length=200)),
                ('linkedin_url', models.URLField(blank=True)),
                ('personal_website', models.URLField(blank=True)),
                ('public_email', models.EmailField(blank=True, help_text='Email shown on the public CV page', max_length=254)),
                ('show_phone_publicly', models.BooleanField(default=False)),
                ('public_slug', models.CharField(default=apps.accounts.models.generate_public_slug, editable=False, max_length=12, unique=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
