# Generated by Django 5.2.16 on 2026-07-15 16:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('documents', '0001_initial'),
        ('research', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='IntellectualProperty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=500)),
                ('ip_type', models.CharField(choices=[('copyright', 'Copyright'), ('patent', 'Patent'), ('trademark', 'Trademark')], max_length=20)),
                ('registration_number', models.CharField(blank=True, max_length=100)),
                ('registration_date', models.DateField()),
                ('description', models.TextField(blank=True)),
                ('is_public', models.BooleanField(default=False)),
                ('certificate', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='intellectual_properties', to='documents.document')),
            ],
            options={
                'verbose_name_plural': 'Intellectual property',
                'ordering': ['-registration_date'],
            },
        ),
        migrations.CreateModel(
            name='Publication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pub_type', models.CharField(choices=[('journal_article', 'Journal Article'), ('conference_paper', 'Conference Paper'), ('book', 'Book'), ('book_chapter', 'Book Chapter')], max_length=20)),
                ('title', models.CharField(max_length=500)),
                ('authors', models.TextField(help_text='Author list in citation order')),
                ('venue', models.CharField(help_text='Journal, conference, or publisher name', max_length=500)),
                ('year', models.PositiveIntegerField()),
                ('volume', models.CharField(blank=True, max_length=50)),
                ('issue', models.CharField(blank=True, max_length=50)),
                ('pages', models.CharField(blank=True, max_length=50)),
                ('doi', models.CharField(blank=True, max_length=255, verbose_name='DOI')),
                ('url', models.URLField(blank=True)),
                ('indexing', models.CharField(choices=[('scopus_q1', 'Scopus Q1'), ('scopus_q2', 'Scopus Q2'), ('scopus_q3', 'Scopus Q3'), ('scopus_q4', 'Scopus Q4'), ('wos', 'Web of Science'), ('sinta_1', 'SINTA 1'), ('sinta_2', 'SINTA 2'), ('sinta_3', 'SINTA 3'), ('sinta_4', 'SINTA 4'), ('sinta_5', 'SINTA 5'), ('sinta_6', 'SINTA 6'), ('other', 'Other'), ('none', 'None')], default='none', max_length=20)),
                ('citation_count', models.PositiveIntegerField(default=0)),
                ('is_corresponding_author', models.BooleanField(default=False)),
                ('is_public', models.BooleanField(default=False)),
                ('grant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='publications', to='research.grant')),
            ],
            options={
                'ordering': ['-year', 'title'],
            },
        ),
    ]
