# Generated by Django 5.2.16 on 2026-07-23 00:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SharedLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Name of document')),
                ('original_url', models.URLField(max_length=1000, verbose_name='Original URL')),
                ('slug', models.SlugField(blank=True, help_text="Custom part of the share link, e.g. 'my-cv'. Auto-generated from the name if left blank.", max_length=80, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
