# Generated by Django 5.2.16 on 2026-07-15 17:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('nim', models.CharField(max_length=50, verbose_name='NIM')),
                ('program', models.CharField(max_length=255)),
                ('thesis_title', models.CharField(blank=True, max_length=500)),
                ('level', models.CharField(choices=[('s1', 'S1'), ('s2', 'S2')], max_length=10)),
                ('status', models.CharField(choices=[('proposal', 'Proposal'), ('in_progress', 'In Progress'), ('seminar', 'Seminar'), ('defended', 'Defended'), ('graduated', 'Graduated'), ('inactive', 'Inactive')], default='proposal', max_length=20)),
                ('start_date', models.DateField()),
                ('target_defense_date', models.DateField(blank=True, null=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Milestone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('due_date', models.DateField()),
                ('completed_date', models.DateField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='milestones', to='supervision.student')),
            ],
            options={
                'ordering': ['due_date'],
            },
        ),
        migrations.CreateModel(
            name='SupervisionLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('mode', models.CharField(choices=[('in_person', 'In Person'), ('online', 'Online')], max_length=10)),
                ('summary', models.TextField()),
                ('next_action', models.TextField(blank=True)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='supervision.student')),
            ],
            options={
                'ordering': ['-date'],
            },
        ),
    ]
