# Generated by Django 5.2.16 on 2026-07-15 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Grant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=500)),
                ('funder', models.CharField(max_length=255)),
                ('grant_number', models.CharField(blank=True, max_length=100)),
                ('scheme', models.CharField(blank=True, max_length=255)),
                ('role', models.CharField(choices=[('pi', 'PI'), ('co_pi', 'Co-PI'), ('member', 'Member')], default='member', max_length=10)),
                ('amount', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('currency', models.CharField(default='IDR', max_length=10)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('proposed', 'Proposed'), ('awarded', 'Awarded'), ('active', 'Active'), ('completed', 'Completed'), ('rejected', 'Rejected')], default='proposed', max_length=20)),
                ('is_public', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ['-start_date'],
            },
        ),
    ]
