# Generated by Django 5.2.16 on 2026-07-15 17:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0001_initial'),
        ('research', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Deliverable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('type', models.CharField(choices=[('report', 'Report'), ('publication', 'Publication'), ('prototype', 'Prototype'), ('ip', 'Intellectual Property')], max_length=20)),
                ('due_date', models.DateField()),
                ('completed', models.BooleanField(default=False)),
                ('document', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='deliverables', to='documents.document')),
                ('grant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deliverables', to='research.grant')),
            ],
            options={
                'ordering': ['due_date'],
            },
        ),
    ]
